/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kartoffel_Licht_CEFFunk */

#ifndef _Included_Kartoffel_Licht_CEFFunk
#define _Included_Kartoffel_Licht_CEFFunk
#ifdef __cplusplus
extern "C" {
#endif
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_DEFAULT
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_DEFAULT 0L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_DEBUG
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_DEBUG 1L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_VERBOSE
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_VERBOSE 2L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_INFO
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_INFO 3L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_WARNING
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_WARNING 4L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_ERROR
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_ERROR 5L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_FATAL
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_FATAL 6L
#undef Kartoffel_Licht_CEFFunk_LOGSEVERITY_DISABLE
#define Kartoffel_Licht_CEFFunk_LOGSEVERITY_DISABLE 7L
#undef Kartoffel_Licht_CEFFunk_MBT_LEFT
#define Kartoffel_Licht_CEFFunk_MBT_LEFT 0L
#undef Kartoffel_Licht_CEFFunk_MBT_RIGHT
#define Kartoffel_Licht_CEFFunk_MBT_RIGHT 1L
#undef Kartoffel_Licht_CEFFunk_MBT_MIDDLE
#define Kartoffel_Licht_CEFFunk_MBT_MIDDLE 2L
#undef Kartoffel_Licht_CEFFunk_KEYEVENT_CHAR
#define Kartoffel_Licht_CEFFunk_KEYEVENT_CHAR 0L
#undef Kartoffel_Licht_CEFFunk_KEYEVENT_KEYDOWN
#define Kartoffel_Licht_CEFFunk_KEYEVENT_KEYDOWN 1L
#undef Kartoffel_Licht_CEFFunk_KEYEVENT_KEYUP
#define Kartoffel_Licht_CEFFunk_KEYEVENT_KEYUP 2L
#undef Kartoffel_Licht_CEFFunk_KEYEVENT_RAWKEYDOWN
#define Kartoffel_Licht_CEFFunk_KEYEVENT_RAWKEYDOWN 3L
#undef Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_IN
#define Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_IN -1L
#undef Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_RESET
#define Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_RESET 0L
#undef Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_OUT
#define Kartoffel_Licht_CEFFunk_CEF_ZOOM_COMMAND_OUT 1L
/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    createNew
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_Kartoffel_Licht_CEFFunk_createNew
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_Kartoffel_Licht_CEFFunk_init
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    doMessageLoopWork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_doMessageLoopWork
  (JNIEnv *, jobject);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_free
  (JNIEnv *, jclass);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    createBrowser
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Kartoffel_Licht_CEFFunk_createBrowser
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    deleteBrowser
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_deleteBrowser
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendMouseClickEvent
 * Signature: (IIIIIZI)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendMouseClickEvent
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendKeyEvent
 * Signature: (ICIII)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendKeyEvent
  (JNIEnv *, jclass, jint, jchar, jint, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendMouseScrollEvent
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendMouseScrollEvent
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendMouseMoveEvent
 * Signature: (IIIIZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendMouseMoveEvent
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendCaptureLostEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendCaptureLostEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    sendExternalBeginFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_sendExternalBeginFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    canGoBack
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Kartoffel_Licht_CEFFunk_canGoBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    canGoForward
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Kartoffel_Licht_CEFFunk_canGoForward
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    goBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_goBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    goForward
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_goForward
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    stopLoading
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_stopLoading
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    isLoading
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Kartoffel_Licht_CEFFunk_isLoading
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    hasDocument
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Kartoffel_Licht_CEFFunk_hasDocument
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    setFramerate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_setFramerate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    reload
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_reload
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    loadURL
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_loadURL
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    viewSource
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_viewSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    cut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_cut
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    copy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_copy
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    paste
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_paste
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    selectall
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_selectall
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_delete
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    undo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_undo
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    redo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_redo
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    canZoom
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Kartoffel_Licht_CEFFunk_canZoom
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    zoom
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_zoom
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    setZoom
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_setZoom
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    setFocus
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_setFocus
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    wasHidden
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_wasHidden
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    wasResized
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_wasResized
  (JNIEnv *, jclass, jint);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    find
 * Signature: (ILjava/lang/String;ZZZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_find
  (JNIEnv *, jclass, jint, jstring, jboolean, jboolean, jboolean);

/*
 * Class:     Kartoffel_Licht_CEFFunk
 * Method:    stopFinding
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_Kartoffel_Licht_CEFFunk_stopFinding
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
